name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Windows:
    name: build-windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: install-make
        run: choco install make
      - name: compile
        run: make build
      - name: run
        run: make run
