name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Linux:
    name: build-windows
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
